[package]
name = "pet_body"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bytemuck.workspace = true
glam.workspace = true
lifecore = { path = "../lifecore" }
pet_audio = { path = "../pet_audio" }
pet_ecology = { path = "../pet_ecology" }
serde.workspace = true
thiserror.workspace = true
wgpu.workspace = true
wgpu-types.workspace = true
winit.workspace = true

[dev-dependencies]
naga.workspace = true
serde_json.workspace = true
