"""Compile untouched generated PNGs into registered, alpha-correct sRGB mip chains.
No painted retouch or recoloring. Every level: LE u32 width,height then RGBA8.
"""
from pathlib import Path
import struct, json, hashlib
from PIL import Image
import numpy as np
folder=Path(__file__).resolve().parent
manifest=json.loads((folder/'manifest.json').read_text())
def linear(v): return np.where(v<=.04045,v/12.92,((v+.055)/1.055)**2.4)
def srgb(v): return np.where(v<=.0031308,12.92*v,1.055*np.maximum(v,0)**(1/2.4)-.055)
for spec in manifest['sources']:
    image=Image.open(folder/(spec['name']+'-source.png')).convert('RGBA')
    if spec['crop']: image=image.crop(spec['crop'])
    image.save(folder/(spec['name']+'.png'))
    rgba=np.asarray(image,dtype=np.float32)/255
    rgba[:,:,:3]=linear(rgba[:,:,:3])*rgba[:,:,3:]
    data=bytearray();sizes=[]
    while True:
        h,w=rgba.shape[:2]; alpha=rgba[:,:,3:]
        color=srgb(rgba[:,:,:3]/np.maximum(alpha,1e-10))
        packed=np.uint8(np.clip(np.concatenate([color,alpha],axis=2)*255+.5,0,255))
        data+=struct.pack('<II',w,h)+packed.tobytes();sizes.append([w,h])
        if w==h==1: break
        next_size=(max(1,w//2),max(1,h//2))
        rgba=np.stack([np.asarray(Image.fromarray(rgba[:,:,c],'F').resize(next_size,Image.Resampling.BOX)) for c in range(4)],axis=2)
    (folder/(spec['name']+'.rgba')).write_bytes(data)
    spec['mip_sizes']=sizes;spec['rgba_sha256']=hashlib.sha256(data).hexdigest()
manifest['runtime_color']='authored sRGB; straight alpha; mip levels averaged in linear premultiplied light, decoded for source-over exactly once'
manifest['mip_format']='Repeated LE u32 width,height + RGBA8 to1x1. Source PNGs remain exact generated bytes.'
(folder/'manifest.json').write_text(json.dumps(manifest,indent=2))
print('Compiled4alpha-correctmipchains.')
